export const agents = [
  {
    id: "claude-code",
    name: "Claude Code",
    initials: "CC",
    state: "reporting",
    evidence: "Event received 2m ago",
    location: "Alex’s MacBook Pro",
    mode: "Observe",
    sessions: 7,
    toolCalls: 31,
    tokens: "184k",
    cost: "$3.82",
    note: "Working normally",
  },
  {
    id: "hermes",
    name: "Hermes",
    initials: "H",
    state: "quiet",
    evidence: "Last event 18m ago",
    location: "Stefan’s Mac mini",
    mode: "Observe",
    sessions: 3,
    toolCalls: 9,
    tokens: "67k",
    cost: "Not reported",
    note: "Enrolled and available",
  },
  {
    id: "pi",
    name: "Pi",
    initials: "π",
    state: "reporting",
    evidence: "Event received just now",
    location: "Alex’s MacBook Pro",
    mode: "Observe",
    sessions: 5,
    toolCalls: 42,
    tokens: "221k",
    cost: "$4.16",
    note: "Working normally",
  },
  {
    id: "codex",
    name: "Codex",
    initials: "CX",
    state: "quiet",
    evidence: "Last event 1h ago",
    location: "Alex’s MacBook Pro",
    mode: "Observe",
    sessions: 1,
    toolCalls: 4,
    tokens: "28k",
    cost: "$0.41",
    note: "No recent activity",
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI",
    initials: "G",
    state: "reporting",
    evidence: "Event received 4m ago",
    location: "Stefan’s Mac mini",
    mode: "Observe",
    sessions: 2,
    toolCalls: 11,
    tokens: "92k",
    cost: "Not reported",
    note: "Working normally",
  },
  {
    id: "cursor",
    name: "Cursor",
    initials: "C",
    state: "not_enrolled",
    evidence: "Discovered, not enrolled",
    location: "Stefan’s Mac mini",
    mode: "Not connected",
    sessions: 0,
    toolCalls: 0,
    tokens: "—",
    cost: "—",
    note: "Finish setup",
  },
];

export const activity = [
  { agent: "Pi", initials: "π", event: "Tool completed", detail: "bash · success · 1.8s", time: "Just now", tone: "sun" },
  { agent: "Claude Code", initials: "CC", event: "Session active", detail: "claude-sonnet · observe only", time: "2m", tone: "blue" },
  { agent: "Gemini CLI", initials: "G", event: "Tool completed", detail: "write_file · success · 320ms", time: "4m", tone: "coral" },
  { agent: "Hermes", initials: "H", event: "Session ended", detail: "3 tools · 11m duration", time: "18m", tone: "violet" },
];

export const environments = [
  { name: "Alex’s MacBook Pro", kind: "Local", agents: 3, evidence: "Reporting now", state: "reporting" },
  { name: "Stefan’s Mac mini", kind: "Local", agents: 3, evidence: "Last event 4m ago", state: "reporting" },
];

export const privacyItems = [
  "Session lifecycle",
  "Tool name and outcome",
  "Duration",
  "Model identity",
  "Token counts",
  "Reported cost",
];

export const excludedItems = [
  "Prompts and messages",
  "Tool arguments and outputs",
  "Commands and file paths",
  "Files and environment values",
  "Credentials",
];
